config/routes.rb
HungryHouse::Application.routes.draw do
  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  match '/signup', :to => 'users#new'
  
  root :to => 'pages#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
    @title = "Contact Us"
  end

  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "Hungry House"
    
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  
  def logo
    image_tag("logo.png", :alt => "Hungry House", :class => "round")
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.alaskageekgirl.com">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%= link_to logo, root_path %>
<nav class="round">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Help", help_path %></li>
		<li><%= link_to "Sign in", '#' %></li>
	</ul>
</nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>	
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div class="container">
		<header>
			<%= render 'layouts/header' %>
		</header>
		<section>	
			<%= yield %>
		</section>
		<footer>
			<%= render 'layouts/footer'%>
		</footer>
	</divs>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Hungry House</h1>
<p>Now you can organize all of your recipes in one place! For real. Hungry House was developed by me, Julie Perilla of alaskageekgirl.com.</p>
<p>I have been developing software for 12 years and cooking for over 20 years. Over the years, I've tried many different recipe applications
and have never found one that does everything that I want it to do. I decided to build my own. In writing the application Hungry House, I strived to make organizing your recipes fun again. The interface is clean and simple, and hopefully you know exactly where to go when you enter the application.</p> 
<p>I'd love to hear your thoughts. Contact me directly at geekgirl16@gmail.com</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>For technical support, questions and feedback, or if you just want to chat with the founder: geekgirl16@gmail.com</p>

app/views/pages/help.html.erb
<h1>Technical Support</h1>
<p>For support, contact us at geekgirl16@gemail.com. Documentation coming soon!</p>

app/views/pages/home.html.erb
<h1>Finally, all of your recipes in one place. For real.</h1>
<p>HungryHouse.com not only allows you to search your favorite recipe sites from one place,
but it lets you import them to a central location, as well as import your printed recipes in books and magazines, and manually enter recipes that are in your head. Once your recipes are entered you can continue to build your recipe empire easily through the web, and sync your recipes with all of your devices. It's easy!</p>
	
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>